version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: wallet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wallgest
      MYSQL_USER: user
      MYSQL_PASSWORD: wallgestPass
    ports:
      - "3311:3311"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wallet_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "808:80"
    depends_on:
      - mysql

  nodeapp:
    build: .
    container_name: wallet_node
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      PORT: 3100
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: wallgestPass
      DB_NAME: wallgest
      DB_DIALECT: mysql

volumes:
  mysql_data:
